In [1]:
import pandas as pd
import scipy.stats as stats

url = "https://raw.githubusercontent.com/dataprofessor/data/refs/heads/master/penguins_cleaned.csv"
# https://raw.githubusercontent.com/dataprofessor/
# data/refs/heads/master/penguins_cleaned.csv

df = pd.read_csv(url)
df.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      333.000000     333.000000         333.000000   333.000000
mean        43.992793      17.164865         200.966967  4207.057057
std          5.468668       1.969235          14.015765   805.215802
min         32.100000      13.100000         172.000000  2700.000000
25%         39.500000      15.600000         190.000000  3550.000000
50%         44.500000      17.300000         197.000000  4050.000000
75%         48.600000      18.700000         213.000000  4775.000000
max         59.600000      21.500000         231.000000  6300.000000

In [ ]:
from classwork.evaluate_df import evaluate_df
# from written source code 
edf = evaluate_df(df)
edf

,column_name,is_numeric,mean,median,min,max,Q25,Q75,std,num_null,num_unique,uniques<5
0,species,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.0,"[Adelie, Gentoo, Chinstrap]"
1,island,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.0,"[Torgersen, Biscoe, Dream]"
6,sex,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2.0,"[male, female]"
2,bill_length_mm,True,43.992793,44.5,32.1,59.6,39.5,48.6,5.468668,0,NaN,NaN
3,bill_depth_mm,True,17.164865,17.3,13.1,21.5,15.6,18.7,1.969235,0,NaN,NaN
4,flipper_length_mm,True,200.966967,197.0,172.0,231.0,190.0,213.0,14.015765,0,NaN,NaN
5,body_mass_g,True,4207.057057,4050.0,2700.0,6300.0,3550.0,4775.0,805.215802,0,NaN,NaN